<a href="https://colab.research.google.com/github/t-abs/Machine-Learning/blob/main/Numpy_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1D Array

In [11]:
import numpy as np
arr=np.array([1,2,3])
print(arr)
type(arr)
print(arr.ndim)
print(arr.shape)

[1 2 3]
1
(3,)


2D Array

In [18]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr[0][1])
print(arr)
print(arr.ndim)
print(arr.shape)

2
[[1 2 3]
 [4 5 6]]
2
(2, 3)


In [10]:
arr=np.array([[[1,2,3],[5,7,8],[9,0,8]]])
print(arr)
print(arr.ndim)

[[[1 2 3]
  [5 7 8]
  [9 0 8]]]
3


Shape of the array-No of elements present in array

In [15]:
arr=np.array([1,2,3,4,5,6,7,8,9,0,8,7])
newarr=arr.reshape(4,3)
print(newarr)
flatten_arr=arr.reshape(-1)
print(flatten_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [0 8 7]]
[1 2 3 4 5 6 7 8 9 0 8 7]


Getting index of array

In [17]:
arr=np.array([1,2,3])
print(arr[0])
print(arr[0] + arr[2])

1
4


Iteration in array

In [20]:
import numpy as np
arr=np.array([1,2,3])
for x in arr:
  print(x)

1
2
3


In [22]:
arr=np.array([[1,2,3],[4,5,6]])
for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


Array Slicing

In [23]:
arr=np.array([1,2,3,4,5])
print(arr[1:4])

[2 3 4]


Array Searching Sorting

In [24]:
arr=np.array([1,2,3,4])
x=np.where(arr==4)
print(x)

(array([3]),)


Find the index where the indexes are even

In [29]:
arr=np.array([1,2,3,4,5,6,7,8,0])
x=np.where(arr%2)
print(x)

(array([0, 2, 4, 6]),)


Sorting

In [31]:
arr=np.array([5,2,3,4])
print(np.sort(arr))

[2 3 4 5]
