<a href="https://colab.research.google.com/github/t-abs/Machine-Learning/blob/main/One_hot_encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

*Target is to convert the text to numeric data*

In [2]:
df=pd.read_csv("/content/homeprices (1).csv")

In [3]:
df

town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [5]:
dummies=pd.get_dummies(df.town)

In [7]:
dummies

monroe township  robinsville  west windsor
0                 1            0             0
1                 1            0             0
2                 1            0             0
3                 1            0             0
4                 1            0             0
5                 0            0             1
6                 0            0             1
7                 0            0             1
8                 0            0             1
9                 0            1             0
10                0            1             0
11                0            1             0
12                0            1             0

In [8]:
merged=pd.concat([df,dummies],axis='columns')
merged

town  area   price  monroe township  robinsville  west windsor
0   monroe township  2600  550000                1            0             0
1   monroe township  3000  565000                1            0             0
2   monroe township  3200  610000                1            0             0
3   monroe township  3600  680000                1            0             0
4   monroe township  4000  725000                1            0             0
5      west windsor  2600  585000                0            0             1
6      west windsor  2800  615000                0            0             1
7      west windsor  3300  650000                0            0             1
8      west windsor  3600  710000                0            0             1
9       robinsville  2600  575000                0            1             0
10      robinsville  2900  600000                0            1             0
11      robinsville  3100  620000                0            1             0
12      robinsville  3600  695000                0            1             0

In [9]:
data=merged.drop(['town','west windsor'],axis='columns')
data

area   price  monroe township  robinsville
0   2600  550000                1            0
1   3000  565000                1            0
2   3200  610000                1            0
3   3600  680000                1            0
4   4000  725000                1            0
5   2600  585000                0            0
6   2800  615000                0            0
7   3300  650000                0            0
8   3600  710000                0            0
9   2600  575000                0            1
10  2900  600000                0            1
11  3100  620000                0            1
12  3600  695000                0            1

In [12]:
from sklearn.linear_model import LinearRegression

In [13]:
model=LinearRegression()

In [14]:
X=data.drop('price',axis='columns')
X

area  monroe township  robinsville
0   2600                1            0
1   3000                1            0
2   3200                1            0
3   3600                1            0
4   4000                1            0
5   2600                0            0
6   2800                0            0
7   3300                0            0
8   3600                0            0
9   2600                0            1
10  2900                0            1
11  3100                0            1
12  3600                0            1

In [17]:
y=data.price

In [18]:
model.fit(X,y)

LinearRegression()

In [20]:
model.predict([[2880,0,1]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([600927.43496023])

In [21]:
model.score(X,y)

0.9573929037221872

In [27]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [28]:
dfle = df
dfle.town = le.fit_transform(dfle.town)
dfle

town  area   price
0      0  2600  550000
1      0  3000  565000
2      0  3200  610000
3      0  3600  680000
4      0  4000  725000
5      2  2600  585000
6      2  2800  615000
7      2  3300  650000
8      2  3600  710000
9      1  2600  575000
10     1  2900  600000
11     1  3100  620000
12     1  3600  695000

In [29]:
X = dfle[['town','area']].values

In [30]:
X

array([[   0, 2600],
       [   0, 3000],
       [   0, 3200],
       [   0, 3600],
       [   0, 4000],
       [   2, 2600],
       [   2, 2800],
       [   2, 3300],
       [   2, 3600],
       [   1, 2600],
       [   1, 2900],
       [   1, 3100],
       [   1, 3600]])

In [31]:
y = dfle.price.values
y

array([550000, 565000, 610000, 680000, 725000, 585000, 615000, 650000,
       710000, 575000, 600000, 620000, 695000])

Exercise

In [32]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [33]:
data=pd.read_csv("/content/carprices.csv")

In [34]:
data.head()

Car Model  Mileage  Sell Price($)  Age(yrs)
0    BMW X5    69000          18000         6
1    BMW X5    35000          34000         3
2    BMW X5    57000          26100         5
3    BMW X5    22500          40000         2
4    BMW X5    46000          31500         4

In [38]:
dummies=pd.get_dummies(data['Car Model'])

In [39]:
dummies

Audi A5  BMW X5  Mercedez Benz C class
0         0       1                      0
1         0       1                      0
2         0       1                      0
3         0       1                      0
4         0       1                      0
5         1       0                      0
6         1       0                      0
7         1       0                      0
8         1       0                      0
9         0       0                      1
10        0       0                      1
11        0       0                      1
12        0       0                      1

In [40]:
merged = pd.concat([df,dummies],axis='columns')
merged

town  area   price  Audi A5  BMW X5  Mercedez Benz C class
0      0  2600  550000        0       1                      0
1      0  3000  565000        0       1                      0
2      0  3200  610000        0       1                      0
3      0  3600  680000        0       1                      0
4      0  4000  725000        0       1                      0
5      2  2600  585000        1       0                      0
6      2  2800  615000        1       0                      0
7      2  3300  650000        1       0                      0
8      2  3600  710000        1       0                      0
9      1  2600  575000        0       0                      1
10     1  2900  600000        0       0                      1
11     1  3100  620000        0       0                      1
12     1  3600  695000        0       0                      1

In [44]:
x = merged.drop(["Mercedez Benz C class"],axis='columns')
x

town  area   price  Audi A5  BMW X5
0      0  2600  550000        0       1
1      0  3000  565000        0       1
2      0  3200  610000        0       1
3      0  3600  680000        0       1
4      0  4000  725000        0       1
5      2  2600  585000        1       0
6      2  2800  615000        1       0
7      2  3300  650000        1       0
8      2  3600  710000        1       0
9      1  2600  575000        0       0
10     1  2900  600000        0       0
11     1  3100  620000        0       0
12     1  3600  695000        0       0

In [45]:
y=merged.price
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [46]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()

In [47]:
lr.fit(x,y)

LinearRegression()

In [50]:
lr.predict([[0,2500,50000,0,0]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([50000.])

In [51]:
lr.score(x,y)

1.0