<a href="https://colab.research.google.com/github/t-abs/Machine-Learning/blob/main/Onehot_encoding_Word_embeding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from keras.preprocessing.text import one_hot

In [5]:
sent=['The glass of milk','the glass of juice','your videos are great','I am good girl','I am a good developer']

In [6]:
sent

['The glass of milk',
 'the glass of juice',
 'your videos are great',
 'I am good girl',
 'I am a good developer']

Vocabulary size

In [7]:
voc_size=10000

In [8]:
one_hotrep=[one_hot(words,voc_size)for words in sent]
print(one_hotrep)

[[1553, 7080, 2772, 8238], [1553, 7080, 2772, 2596], [6555, 1441, 6376, 7717], [2353, 1759, 9523, 5705], [2353, 1759, 1039, 9523, 7469]]


In [9]:
!pip install tensorflow

In [10]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences

from tensorflow.keras.models import Sequential


In [11]:
import numpy as np

In [13]:
sent_length=8
embeded_docs=pad_sequences(one_hotrep,padding='pre',maxlen=sent_length)
print(embeded_docs)

[[   0    0    0    0 1553 7080 2772 8238]
 [   0    0    0    0 1553 7080 2772 2596]
 [   0    0    0    0 6555 1441 6376 7717]
 [   0    0    0    0 2353 1759 9523 5705]
 [   0    0    0 2353 1759 1039 9523 7469]]


In [14]:
dim=15

In [15]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [16]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [17]:
print(model.predict(embeded_docs))

1/1 [==============================] - 0s 121ms/step
[[[-0.03296932 -0.04979329  0.01610681 -0.03664309  0.01639262
   -0.01641617 -0.0368466   0.04517699  0.02224607 -0.01021619]
  [-0.03296932 -0.04979329  0.01610681 -0.03664309  0.01639262
   -0.01641617 -0.0368466   0.04517699  0.02224607 -0.01021619]
  [-0.03296932 -0.04979329  0.01610681 -0.03664309  0.01639262
   -0.01641617 -0.0368466   0.04517699  0.02224607 -0.01021619]
  [-0.03296932 -0.04979329  0.01610681 -0.03664309  0.01639262
   -0.01641617 -0.0368466   0.04517699  0.02224607 -0.01021619]
  [ 0.02760997  0.0466596  -0.00169413 -0.04071571  0.02830282
   -0.04651764  0.04362143  0.0482134   0.03335596  0.00416155]
  [-0.0109803  -0.01369636  0.00600129 -0.04593991  0.02237571
   -0.04301618  0.04466267  0.00953919  0.03080258 -0.00971171]
  [ 0.03116227  0.02067817 -0.00213653  0.00773001 -0.0021866
   -0.04657185  0.03423751  0.03254587  0.00628824  0.02035198]
  [ 0.04435704  0.01990862 -0.00354696 -0.0004493   0.00275

In [18]:
embeded_docs[0]

array([   0,    0,    0,    0, 1553, 7080, 2772, 8238], dtype=int32)